name: Fetch data

on:
  workflow_dispatch:
  schedule:
    # Runs every 30 minutes
    - cron: "*/30 * * * *"
  push:
    branches:
      - main
    paths:
      - "script/**"
      - ".github/workflows/fetch_data.yml"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v3
      - name: Setup
        run: |
          corepack enable
          yarn global add typescript
          cd script
          yarn install
      - name: Run fetch script
        run: |
          cd script
          yarn run run ${{ secrets.API_TOKEN_GITHUB }}
