name: Fetch data

on:
  workflow_dispatch:
  schedule:
    # Runs every 15 minutes
    - cron: "*/15 * * * *"
  push:
    paths:
      - "script/**"
      - ".github/workflows/fetch_data.yml"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v3
      - name: Setup
        run: |
          corepack enable
          yarn global add typescript
          cd script
          yarn install
      - name: Run fetch script
        run: |
          cd script
          yarn run build
          node out/index.js ${{ secrets.API_TOKEN_GITHUB }}
      # - name: Upload to data branch
      #   uses: dmnemec/copy_file_to_another_repo_action@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source_file: "script/data/"
      #     destination_repo: "SiongSng/Rapid-Antigen-Test-Taiwan-Map"
      #     destination_branch: "data"
      #     user_email: "github-actions[bot]@github.com"
      #     user_name: "GitHub Actions Bot"
      #     commit_message: "Auto update data"
